In [2]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444], 'col3':['abc', 'def', 'ghi', 'xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [8]:
df['col2'].unique()
# get unique values of a column

array([444, 555, 666])

In [10]:
df['col2'].nunique()
# get the number of unique values

3

In [12]:
df['col2'].value_counts()
# get unqiue values and count the amount in a column

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [16]:
newdf = df[(df['col1'] > 2) & (df['col2'] == 444)]
newdf
# create a new dataframe based on df, where the value of col1 is greather then 2 and col2 is equal 444

   col1  col2 col3
3     4   444  xyz

In [17]:
def multiply2(x):
    return x * 2
# define a function that multiplies by 2

In [19]:
df['col2'].apply(multiply2)
# apply the function to column 2

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [21]:
df['col3'].apply(len)
# return the string length of column 3 with the len function

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [22]:
df['col2'].apply(lambda x: x * 2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [23]:
df['col2'].min()

444

In [25]:
df.drop('col2', axis = 1)
# remove a column from a dataframe (not permanent)

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [26]:
del df['col1']
# delete a column from a dataframe

In [27]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [29]:
df.columns
# return all column names

Index(['col2', 'col3'], dtype='object')

In [31]:
df.index
# information about the rows

RangeIndex(start=0, stop=4, step=1)

In [32]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [35]:
df.sort_values(by = 'col2', ascending = False, inplace = True)
# sort the dataframe by column 2 descending

In [36]:
df

   col2 col3
2   666  ghi
1   555  def
0   444  abc
3   444  xyz

In [37]:
df.isnull()
# returns null values of the dataframe

    col2   col3
2  False  False
1  False  False
0  False  False
3  False  False

In [38]:
df.dropna()

   col2 col3
2   666  ghi
1   555  def
0   444  abc
3   444  xyz

In [3]:
import numpy as np
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [4]:
df.fillna(0)
# fill NaN values with 0

   col1   col2 col3
0   1.0    0.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz

In [5]:
df['col1'] = df['col1'].fillna(df['col1'].mean())
df['col2'] = df['col2'].fillna(df['col2'].mean())
# fill the NaN values of the two columns with their mean value

In [6]:
df

   col1   col2 col3
0   1.0  555.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   2.0  444.0  xyz

In [7]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [8]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [15]:
df.pivot_table(values = 'D', index = ['A','B'], columns = ['C'])
# pivoting a table

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN