In [2]:
import pandas as pd

data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'], 
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Anne', 'Karl'], 
        'Sales': [200,120,340,124,243,350]}
#create data

In [14]:
df = pd.DataFrame(data)
#create dataframe from data

In [6]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Anne    243
5      FB     Karl    350

In [13]:
df.groupby('Company')['Sales'].mean()
#get the mean value of each group. Grouped by company. 
#The requested group value needs to be passed too. 
#In this case it is 'Sales'

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [15]:
by_company = df.groupby('Company')
#group by company

In [21]:
by_company['Sales'].std()
#standard deviation per group

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [25]:
by_company['Sales'].min()
#min per company

Company
FB      243
GOOG    120
MSFT    124
Name: Sales, dtype: int64

In [26]:
by_company['Sales'].count()
#count the amount of sales per company

Company
FB      2
GOOG    2
MSFT    2
Name: Sales, dtype: int64

In [28]:
by_company.describe()
#retrieve information by group

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [30]:
by_company.describe().transpose()
#transpose the matrix

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [31]:
by_company.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64