In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [2]:
outer = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inner = [1, 2, 3, 1, 2, 3]
#creation of outer and inner index
h_index = list(zip(outer, inner))
h_index = pd.MultiIndex.from_tuples(h_index)
#hierarchical index

In [11]:
h_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [3]:
df = pd.DataFrame(np.random.randn(6,2),index = h_index, columns = ['A', 'B'])
#generate a daraframe with multiindex

In [14]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [4]:
df.loc['G1']
#output only the outer index 'G1'

          A         B
1  2.706850  0.628133
2  0.907969  0.503826
3  0.651118 -0.319318

In [5]:
df.loc['G1'].loc[2]
#access the inner index  2 0f 'G1'

A    0.907969
B    0.503826
Name: 2, dtype: float64

In [7]:
df.index.names = ['Group', 'Num']
#set name for the outer indices

In [8]:
df

                  A         B
Group Num
G1    1    2.706850  0.628133
      2    0.907969  0.503826
      3    0.651118 -0.319318
G2    1   -0.848077  0.605965
      2   -2.018168  0.740122
      3    0.528813 -0.589001

In [9]:
df.xs('G1')
#cross section of a index

            A         B
Num
1    2.706850  0.628133
2    0.907969  0.503826
3    0.651118 -0.319318

In [12]:
df.xs(('G1',1))
#get Num 1 of Group G1

A    2.706850
B    0.628133
Name: (G1, 1), dtype: float64

In [16]:
df.xs(1, level = 'Num')
#return all outer index values where the Num index is 1

              A         B
Group
G1     2.706850  0.628133
G2    -0.848077  0.605965