In [2]:
import numpy as np
import pandas as pd

In [3]:
from numpy.random import randn

In [4]:
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [6]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
df['W']

A    0.386030
B    0.681209
C   -1.005187
D   -1.382920
E    0.992573
Name: W, dtype: float64

In [12]:
df[['W', 'X']]

          W         X
A  0.386030  2.084019
B  0.681209  1.035125
C -1.005187 -0.741790
D -1.382920  1.482495
E  0.992573  1.192241

In [13]:
df.W

A    0.386030
B    0.681209
C   -1.005187
D   -1.382920
E    0.992573
Name: W, dtype: float64

In [14]:
type(df.W)

pandas.core.series.Series

In [17]:
df['new'] = df['W'] + df['Y']
#adding a new column to a dataframe based on existing columns

In [18]:
df

          W         X         Y         Z       new
A  0.386030  2.084019 -0.376519  0.230336  0.009512
B  0.681209  1.035125 -0.031160  1.939932  0.650049
C -1.005187 -0.741790  0.187125 -0.732845 -0.818062
D -1.382920  1.482495  0.961458 -2.141212 -0.421462
E  0.992573  1.192241 -1.046780  1.292765 -0.054206

In [25]:
df.drop('new', axis = 1)
#not permanent

          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [26]:
df.drop('new', axis = 1, inplace = True)
#delete column permanent

In [27]:
df

          W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [28]:
df.drop('A', axis = 0)
#delete a row

          W         X         Y         Z
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [30]:
df.loc['A']
#access a row of a dataframe

W    0.386030
X    2.084019
Y   -0.376519
Z    0.230336
Name: A, dtype: float64

In [31]:
df.iloc[1]
#access the index of a row

W    0.681209
X    1.035125
Y   -0.031160
Z    1.939932
Name: B, dtype: float64

In [11]:
df.loc['B', 'Y']
#access a specific value in a column, row combination
#same can be done with iloc for the index

np.float64(-0.8480769834036315)

In [12]:
df.loc[['A','B'],['W','Z']]
#access a specific subset of a dataframe

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965