In [2]:
import numpy as np
import pandas as pd

In [3]:
from numpy.random import randn

In [4]:
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [6]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
df > 0
#returns true if the cell value is greater then 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [8]:
df[df > 0]
#return only values that are greater 0, otherwise return NaN

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [9]:
df['W'] > 0
#only return true or false for a specific colum

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [11]:
df[df['W'] > 0]
#returns the dataframe but ONLY where the values in column 'W' is greather then zero in the rows.

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df[df['W'] > 0]['Y']
#same as previous, but it only displays column 'Y'

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [14]:
df[df['W'] > 0][['X','Y']]
#output of multiple columns where 'W' is greather then zero for the roews

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [18]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [17]:
df[(df['W'] > 0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [19]:
df[(df['W'] > 0) | (df['Y'] > 1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
df.reset_index()
#reset the index, current index becomes a column named 'index'

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [22]:
new_index = 'BY BY HH BB NW'.split()
#create a new index

In [23]:
df["States"] = new_index
#assign the new index to the dataframe

In [24]:
df
#print dataframe with the new index

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     BY
B  0.651118 -0.319318 -0.848077  0.605965     BY
C -2.018168  0.740122  0.528813 -0.589001     HH
D  0.188695 -0.758872 -0.933237  0.955057     BB
E  0.190794  1.978757  2.605967  0.683509     NW

In [26]:
df.set_index('States')
#change the index temporary to the column 'States'

               W         X         Y         Z
States
BY      2.706850  0.628133  0.907969  0.503826
BY      0.651118 -0.319318 -0.848077  0.605965
HH     -2.018168  0.740122  0.528813 -0.589001
BB      0.188695 -0.758872 -0.933237  0.955057
NW      0.190794  1.978757  2.605967  0.683509

In [27]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     BY
B  0.651118 -0.319318 -0.848077  0.605965     BY
C -2.018168  0.740122  0.528813 -0.589001     HH
D  0.188695 -0.758872 -0.933237  0.955057     BB
E  0.190794  1.978757  2.605967  0.683509     NW

In [28]:
df.set_index('States', inplace = True)
#override the current index with the new index

In [29]:
df

               W         X         Y         Z
States
BY      2.706850  0.628133  0.907969  0.503826
BY      0.651118 -0.319318 -0.848077  0.605965
HH     -2.018168  0.740122  0.528813 -0.589001
BB      0.188695 -0.758872 -0.933237  0.955057
NW      0.190794  1.978757  2.605967  0.683509